/**
 * Offline training script for the food-calorie calibration model — NOT deployed as a Cloud
 * Function. Run manually (`npm run train:calories` from functions/) to (re)generate
 * model/calorieWeights.generated.ts, which compiles straight into analyzeFoodPhoto.ts with zero
 * runtime file-loading, mirroring ml/train.ts's approach for the habit model.
 */

import * as fs from 'fs';
import * as path from 'path';
import { generateCalorieDataset, splitTrainValidation, toVectorsAndLabels } from './calorieSyntheticData';
import { trainLinearRegression, evaluateMAE } from '../ml/linearRegression';
import { CATEGORY_NAMES } from './nutritionReference';

function main() {
  console.log('Generating synthetic calorie training data...');
  const dataset = generateCalorieDataset(60);
  const { train, validation } = splitTrainValidation(dataset, 0.2);
  console.log(`  ${train.length} training samples, ${validation.length} validation samples`);

  const { vectors: trainVectors, labels: trainLabels } = toVectorsAndLabels(train);
  const { vectors: valVectors, labels: valLabels } = toVectorsAndLabels(validation);

  console.log('Training linear regression...');
  const { model, lossHistory } = trainLinearRegression(trainVectors, trainLabels, {
    epochs: 300,
    learningRate: 0.1,
    l2: 0.001,
    batchSize: 32,
  });
  console.log(`  MSE: ${lossHistory[0]?.toFixed(1)} -> ${lossHistory[lossHistory.length - 1]?.toFixed(1)}`);

  const trainMAE = evaluateMAE(model, trainVectors, trainLabels);
  const valMAE = evaluateMAE(model, valVectors, valLabels);

  // Naive baseline: always predict the training-set mean calorie value, regardless of portion/category.
  const meanLabel = trainLabels.reduce((sum, y) => sum + y, 0) / trainLabels.length;
  const baselineMAE = valLabels.reduce((sum, y) => sum + Math.abs(y - meanLabel), 0) / valLabels.length;

  console.log(`  train MAE: ${trainMAE.toFixed(1)} kcal`);
  console.log(`  validation MAE: ${valMAE.toFixed(1)} kcal`);
  console.log(`  validation baseline MAE (always predict mean): ${baselineMAE.toFixed(1)} kcal`);

  const outputPath = path.join(__dirname, 'model', 'calorieWeights.generated.ts');
  const fileContent = `/**
 * AUTO-GENERATED by src/food/trainCalorieModel.ts — do not edit by hand, re-run
 * \`npm run train:calories\` instead.
 * Trained on synthetic data (see calorieSyntheticData.ts) built around the curated reference
 * table in nutritionReference.ts.
 *
 * Feature order: portionGramsNorm, ${CATEGORY_NAMES.join(', ')}
 * Train MAE: ${trainMAE.toFixed(1)} kcal
 * Validation MAE: ${valMAE.toFixed(1)} kcal
 * Validation baseline MAE (always predict mean): ${baselineMAE.toFixed(1)} kcal
 */
import type { TrainedLinearModel } from '../../ml/linearRegression';

export const calorieModel: TrainedLinearModel = ${JSON.stringify(model, null, 2)};

export const calorieTrainingMetadata = {
  trainMAE: ${trainMAE},
  validationMAE: ${valMAE},
  validationBaselineMAE: ${baselineMAE},
  categoryNames: ${JSON.stringify(CATEGORY_NAMES)},
};
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, fileContent);
  console.log(`Wrote trained calorie model to ${outputPath}`);
}

main();
