/**
 * AUTO-GENERATED by ml_python/train_habit_recommender.py — do not edit by hand.
 * Re-run with `npm run train` (which invokes the Python trainer).
 *
 * Fitted with scikit-learn LogisticRegression (L2, lbfgs) on 600 simulated users x
 * 40 days (24000 rows) across 6 behavioural archetypes. Python trains; the phone
 * only evaluates a dot product and a sigmoid, which is why recommendations work offline.
 *
 * All data is synthetic: these figures measure how well the pipeline recovers a relationship the
 * generator encodes, not real-world human behaviour.
 *
 * Validation (8000 rows, 200 unseen users):
 *   positive rate     61.0%
 *   accuracy          73.0%  (always-yes baseline 61.0%)
 *   F1                80.6%  (always-yes baseline 75.8%)
 *   Bayes ceiling     73.4%
 *   ROC AUC           0.7501
 *   Brier skill       0.2216
 *
 * Top-1 hour selection, 1500 held-out users (lower regret is better):
 *   trained model              regret   6.18  top-1 54.5%  within-1h 92.9%
 *   argmax(historical rate)    regret  10.73  top-1 36.1%  within-1h 72.2%
 *   user's preferred hour      regret  10.14  top-1 34.2%  within-1h 74.3%
 *   random hour                regret  39.11  top-1 6.3%  within-1h 18.1%
 *   fixed 06:00                regret  49.09  top-1 0.0%  within-1h 17.3%
 *
 * Pre-registered criterion (beat both the historical-rate and preferred-hour policies): MET
 */
import type { TrainedModel } from '../logisticRegression';

export const trainedModel: TrainedModel = {
  "weights": [
    -0.016976754848345404,
    0.5442510842748223,
    -0.06049839482512025,
    0.07859827340935345,
    0.24784430514913286,
    0.07521548787156411,
    -0.0821572288037264,
    0.4895942077048922,
    -0.38339926629457594
  ],
  "bias": 0.3792191324727204,
  "featureMeans": [
    0.02535259254602991,
    0.6811562171571522,
    0.25,
    0.5722619857011536,
    0.5138023104549836,
    0.11750595238095672,
    0.32500000000000223,
    0.9241666666666667,
    0.3295416666666667
  ],
  "featureStds": [
    0.4734161419377545,
    0.557907349326107,
    0.4330127018922193,
    0.09867797429015211,
    0.2211117277566283,
    0.1656509139869089,
    0.1923899396769128,
    0.26473125786147045,
    0.4700467600113655
  ],
  "featureNames": [
    "hourOffsetSin",
    "hourOffsetCos",
    "isWeekend",
    "historicalSuccessRate",
    "evidenceNorm",
    "streakNorm",
    "habitAgeNorm",
    "isAwake",
    "isDuringWork"
  ]
};

export const trainingMetadata = {
  "trainMetrics": {
    "n": 24000,
    "positiveRate": 0.5990833333333333,
    "accuracy": 0.7159166666666666,
    "precision": 0.7046340407102641,
    "recall": 0.9052719432466267,
    "f1": 0.7924505327245053,
    "alwaysYesAccuracy": 0.5990833333333333,
    "alwaysYesF1": 0.7492834436395852,
    "rocAuc": 0.7526167602476115,
    "brier": 0.1890418810687928,
    "brierSkillScore": 0.21292397849719058,
    "bayesCeilingAccuracy": 0.7240093466642288
  },
  "valMetrics": {
    "n": 8000,
    "positiveRate": 0.609875,
    "accuracy": 0.73025,
    "precision": 0.7187650747708635,
    "recall": 0.9161713465874155,
    "f1": 0.8055505496485853,
    "alwaysYesAccuracy": 0.609875,
    "alwaysYesF1": 0.7576675207702461,
    "rocAuc": 0.7500604011503242,
    "brier": 0.18520097792811555,
    "brierSkillScore": 0.22160746407834786,
    "bayesCeilingAccuracy": 0.7338126553080467
  },
  "ranking": [
    {
      "name": "trained model",
      "meanRegret": 6.183323174649315,
      "top1": 54.46666666666667,
      "within1h": 92.86666666666666
    },
    {
      "name": "argmax(historical rate)",
      "meanRegret": 10.729283540131858,
      "top1": 36.13333333333333,
      "within1h": 72.2
    },
    {
      "name": "user's preferred hour",
      "meanRegret": 10.13869686279092,
      "top1": 34.2,
      "within1h": 74.26666666666667
    },
    {
      "name": "random hour",
      "meanRegret": 39.10726977277541,
      "top1": 6.266666666666667,
      "within1h": 18.133333333333333
    },
    {
      "name": "fixed 06:00",
      "meanRegret": 49.08742986687097,
      "top1": 0.0,
      "within1h": 17.333333333333332
    }
  ],
  "trainUsers": 600,
  "valUsers": 200,
  "days": 40
};
