/**
 * Offline training script — NOT deployed as a Cloud Function. Run manually
 * (`npm run train` from functions/) whenever the model needs retraining. Generates a
 * rich synthetic dataset, trains logistic regression via gradient descent, evaluates
 * on a held-out split, and writes learned weights to model/weights.generated.ts.
 */

import * as fs from 'fs';
import * as path from 'path';
import { generateSyntheticDataset, splitTrainValidation, toVectorsAndLabels } from './syntheticData';
import { trainLogisticRegression, evaluateAccuracy, predictProbability, type TrainedModel } from './logisticRegression';
import { FEATURE_NAMES } from './features';

interface DetailedMetrics {
  accuracy: number;
  precision: number;
  recall: number;
  f1: number;
  tp: number;
  fp: number;
  tn: number;
  fn: number;
  majorityBaseline: number;
}

function computeDetailedMetrics(model: TrainedModel, vectors: number[][], labels: number[]): DetailedMetrics {
  let tp = 0;
  let fp = 0;
  let tn = 0;
  let fn = 0;
  let positiveCount = 0;

  for (let i = 0; i < vectors.length; i++) {
    const actual = labels[i];
    if (actual === 1) positiveCount++;

    const prob = predictProbability(model, vectors[i]);
    const pred = prob >= 0.5 ? 1 : 0;

    if (pred === 1 && actual === 1) tp++;
    else if (pred === 1 && actual === 0) fp++;
    else if (pred === 0 && actual === 0) tn++;
    else if (pred === 0 && actual === 1) fn++;
  }

  const accuracy = (tp + tn) / vectors.length;
  const precision = tp + fp > 0 ? tp / (tp + fp) : 0;
  const recall = tp + fn > 0 ? tp / (tp + fn) : 0;
  const f1 = precision + recall > 0 ? (2 * precision * recall) / (precision + recall) : 0;
  const majorityBaseline = Math.max(positiveCount, vectors.length - positiveCount) / vectors.length;

  return { accuracy, precision, recall, f1, tp, fp, tn, fn, majorityBaseline };
}

function main() {
  console.log('====================================================');
  console.log(' LifeSync AI Habit Recommender — Supervised ML Train');
  console.log('====================================================');
  console.log('Generating realistic multi-archetype synthetic dataset...');
  
  // 500 users x 40 days = 20,000 samples
  const dataset = generateSyntheticDataset(500, 40);
  const { train, validation } = splitTrainValidation(dataset, 0.2);
  console.log(`  Total samples: ${dataset.length} (${train.length} train, ${validation.length} validation)`);

  const { vectors: trainVectors, labels: trainLabels } = toVectorsAndLabels(train);
  const { vectors: valVectors, labels: valLabels } = toVectorsAndLabels(validation);

  console.log('\nTraining Logistic Regression via Mini-Batch Gradient Descent...');
  const { model, lossHistory } = trainLogisticRegression(trainVectors, trainLabels, {
    epochs: 400,
    learningRate: 0.12,
    l2: 0.0008,
    batchSize: 32,
  });

  const initialLoss = lossHistory[0] ?? 0;
  const finalLoss = lossHistory[lossHistory.length - 1] ?? 0;
  console.log(`  Convergence: Binary Cross-Entropy loss reduced from ${initialLoss.toFixed(4)} -> ${finalLoss.toFixed(4)}`);

  const trainMetrics = computeDetailedMetrics(model, trainVectors, trainLabels);
  const valMetrics = computeDetailedMetrics(model, valVectors, valLabels);

  console.log('\n--- Evaluation Metrics ---');
  console.log(`  Train Accuracy:      ${(trainMetrics.accuracy * 100).toFixed(1)}%`);
  console.log(`  Validation Accuracy: ${(valMetrics.accuracy * 100).toFixed(1)}%`);
  console.log(`  Validation Precision: ${(valMetrics.precision * 100).toFixed(1)}%`);
  console.log(`  Validation Recall:    ${(valMetrics.recall * 100).toFixed(1)}%`);
  console.log(`  Validation F1-Score:  ${(valMetrics.f1 * 100).toFixed(1)}%`);
  console.log(`  Majority Baseline:    ${(valMetrics.majorityBaseline * 100).toFixed(1)}%`);
  console.log(`  Predictive Lift:      +${((valMetrics.accuracy - valMetrics.majorityBaseline) * 100).toFixed(1)} percentage points`);

  console.log('\n--- Validation Confusion Matrix ---');
  console.log(`  TP: ${valMetrics.tp} | FP: ${valMetrics.fp}`);
  console.log(`  FN: ${valMetrics.fn} | TN: ${valMetrics.tn}`);

  console.log('\n--- Learned Feature Weights ---');
  const rankedFeatures = FEATURE_NAMES.map((name, i) => ({
    name,
    weight: model.weights[i],
    absWeight: Math.abs(model.weights[i]),
  })).sort((a, b) => b.absWeight - a.absWeight);

  rankedFeatures.forEach((f, idx) => {
    console.log(`  ${idx + 1}. ${f.name.padEnd(24)}: ${f.weight >= 0 ? '+' : ''}${f.weight.toFixed(4)}`);
  });
  console.log(`  Bias: ${model.bias >= 0 ? '+' : ''}${model.bias.toFixed(4)}`);

  const outputPath = path.join(__dirname, 'model', 'weights.generated.ts');
  const fileContent = `/**
 * AUTO-GENERATED by src/ml/train.ts — do not edit by hand, re-run \`npm run train\` instead.
 * Trained on a synthetic dataset of 500 simulated users x 40 days (20,000 samples)
 * across 6 realistic behavioral archetypes.
 *
 * Feature order: ${FEATURE_NAMES.join(', ')}
 * Train accuracy: ${(trainMetrics.accuracy * 100).toFixed(1)}%
 * Validation accuracy: ${(valMetrics.accuracy * 100).toFixed(1)}%
 * Validation F1: ${(valMetrics.f1 * 100).toFixed(1)}%
 * Baseline lift: +${((valMetrics.accuracy - valMetrics.majorityBaseline) * 100).toFixed(1)}%
 */
import type { TrainedModel } from '../logisticRegression';

export const trainedModel: TrainedModel = ${JSON.stringify(model, null, 2)};

export const trainingMetadata = {
  trainAccuracy: ${trainMetrics.accuracy},
  validationAccuracy: ${valMetrics.accuracy},
  validationPrecision: ${valMetrics.precision},
  validationRecall: ${valMetrics.recall},
  validationF1: ${valMetrics.f1},
  majorityBaseline: ${valMetrics.majorityBaseline},
  featureNames: ${JSON.stringify(FEATURE_NAMES)},
  lossHistory: ${JSON.stringify(lossHistory)},
  confusionMatrix: {
    tp: ${valMetrics.tp},
    fp: ${valMetrics.fp},
    tn: ${valMetrics.tn},
    fn: ${valMetrics.fn},
  },
};
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, fileContent);
  console.log(`\nSuccessfully wrote trained model & metadata to ${outputPath}`);
}

main();

