/**
 * Firestore Database Seeder for LifeSync.
 *
 * Populates Firestore with rich, realistic dummy data:
 * - User Profile (Daily goals, routine times, preferences)
 * - 5 Realistic Habits
 * - WINDOW_DAYS days of Habit Completion Logs (with natural streaks and circadian patterns)
 * - WINDOW_DAYS days of Health Metrics (Sleep hours, Water intake, Step counts)
 * - WINDOW_DAYS days of Multimodal Food Logs (Calories, Macros, Condition, Health Tips)
 * - Pre-computed AI Recommendations generated by the trained ML model
 *
 * Usage:
 *   npx ts-node --transpile-only src/seed/seedDatabase.ts [--uid=CUSTOM_UID] [--project=PROJECT_ID]
 *   npx ts-node --transpile-only src/seed/seedDatabase.ts --email=someone@example.com [--project=PROJECT_ID]
 *
 * --email targets a REAL existing user (resolved to their UID via Firebase Auth) instead of the
 * demo-user-123 default. In that mode, the user's existing profile fields (displayName, email,
 * goals, etc.) are left untouched — only `createdAt` (their "joined" date) is merged in, backdated
 * to just before the seeded window, so the seeded history doesn't predate account creation.
 * This writes to whatever Firestore project your credentials point at (real production data if
 * you're authenticated against the live project) — double check GCLOUD_PROJECT / your
 * GOOGLE_APPLICATION_CREDENTIALS before running against anything but the emulator.
 */

import { initializeApp } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { getAuth } from 'firebase-admin/auth';
import { recommendHourWithModel, CANDIDATE_HOURS, type MlContext } from '../ml/mlRecommender';
import { hourKernelSuccessRate, RECENCY_DECAY, type HourlyAttempt } from '../ml/historicalRate';

// If FIRESTORE_EMULATOR_HOST is set, it connects locally.
if (!process.env.FIRESTORE_EMULATOR_HOST && !process.env.GOOGLE_APPLICATION_CREDENTIALS) {
  process.env.FIRESTORE_EMULATOR_HOST = process.env.FIRESTORE_EMULATOR_HOST || '127.0.0.1:8080';
}

const app = initializeApp({ projectId: process.env.GCLOUD_PROJECT || 'demo-lifesync' });
const db = getFirestore();

// How many days of habit/health/food history to seed — "3 weeks" per the request that prompted
// --email mode; kept as a single constant so every collection stays in sync.
const WINDOW_DAYS = 21;

// Parse CLI arguments
const args = process.argv.slice(2);
let targetUid = 'demo-user-123';
let targetEmail: string | null = null;
for (const arg of args) {
  if (arg.startsWith('--uid=')) targetUid = arg.split('=')[1];
  if (arg.startsWith('--email=')) targetEmail = arg.split('=')[1];
}

console.log('====================================================');
console.log(' LifeSync Firestore Database Seeder');
console.log('====================================================');
console.log(`Firestore Host:  ${process.env.FIRESTORE_EMULATOR_HOST || 'Live Firebase Cloud'}`);

function formatDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function daysAgoDate(days: number): Date {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() - days);
  return d;
}

const SAMPLE_HABITS = [
  {
    id: 'habit-workout',
    title: 'Morning Cardio & Workout',
    preferredTime: '07:00',
    recurring: true,
    daysOfWeek: [1, 2, 3, 4, 5, 6],
    ageDays: 35,
    preferredHour: 7,
    consistency: 0.85,
  },
  {
    id: 'habit-hydration',
    title: 'Hydration & Mindful Stretch',
    preferredTime: '11:00',
    recurring: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    ageDays: 35,
    preferredHour: 11,
    consistency: 0.90,
  },
  {
    id: 'habit-study',
    title: 'Read Research Papers & Book',
    preferredTime: '21:00',
    recurring: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    ageDays: 35,
    preferredHour: 21,
    consistency: 0.88,
  },
  {
    id: 'habit-meditation',
    title: 'Mindfulness Meditation',
    preferredTime: '06:45',
    recurring: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    ageDays: 30,
    preferredHour: 6,
    consistency: 0.78,
  },
  {
    id: 'habit-evening-walk',
    title: 'Sunset Outdoor Walk',
    preferredTime: '18:00',
    recurring: true,
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    ageDays: 25,
    preferredHour: 18,
    consistency: 0.82,
  },
];

const SAMPLE_MEALS = [
  {
    name: 'Grilled Herb Chicken & Quinoa Bowl',
    items: [
      { name: 'Grilled Chicken Breast', estimatedPortion: '180g', estimatedPortionGrams: 180, calories: 290, matchedCategory: 'chicken_breast' },
      { name: 'Cooked Quinoa & Avocado', estimatedPortion: '150g', estimatedPortionGrams: 150, calories: 220, matchedCategory: 'quinoa' },
      { name: 'Mixed Leaf Greens with Olive Oil', estimatedPortion: '80g', estimatedPortionGrams: 80, calories: 95, matchedCategory: 'salad' },
    ],
    totalCalories: 605,
    macros: { proteinGrams: 48, carbsGrams: 42, fatGrams: 16 },
    condition: 'Fresh, vibrant, well-portioned whole foods',
    healthTip: 'Excellent protein density to support muscle recovery and sustained afternoon energy.',
    confidence: 0.96,
  },
  {
    name: 'Oatmeal with Fresh Blueberries & Honey',
    items: [
      { name: 'Rolled Oats with Almond Milk', estimatedPortion: '200g', estimatedPortionGrams: 200, calories: 240, matchedCategory: 'oatmeal' },
      { name: 'Fresh Blueberries', estimatedPortion: '60g', estimatedPortionGrams: 60, calories: 45, matchedCategory: 'blueberries' },
      { name: 'Raw Honey & Chia Seeds', estimatedPortion: '25g', estimatedPortionGrams: 25, calories: 85, matchedCategory: 'chia_seeds' },
    ],
    totalCalories: 370,
    macros: { proteinGrams: 12, carbsGrams: 64, fatGrams: 7 },
    condition: 'Nutrient-rich, fresh antioxidant-dense breakfast',
    healthTip: 'Complex carbohydrates provide slow-release glucose ideal for early morning focus.',
    confidence: 0.98,
  },
  {
    name: 'Atlantic Salmon with Steamed Greens & Rice',
    items: [
      { name: 'Pan-Seared Atlantic Salmon', estimatedPortion: '200g', estimatedPortionGrams: 200, calories: 410, matchedCategory: 'salmon' },
      { name: 'Steamed Jasmine Rice', estimatedPortion: '150g', estimatedPortionGrams: 150, calories: 195, matchedCategory: 'rice' },
      { name: 'Steamed Broccoli & Asparagus', estimatedPortion: '120g', estimatedPortionGrams: 120, calories: 45, matchedCategory: 'broccoli' },
    ],
    totalCalories: 650,
    macros: { proteinGrams: 44, carbsGrams: 52, fatGrams: 22 },
    condition: 'Freshly prepared, balanced omega-3 rich dinner',
    healthTip: 'Rich in anti-inflammatory Omega-3 fatty acids that enhance cognitive recovery.',
    confidence: 0.95,
  },
  {
    name: 'Greek Yogurt Parfait with Walnuts',
    items: [
      { name: 'Greek Yogurt 0% Fat', estimatedPortion: '200g', estimatedPortionGrams: 200, calories: 130, matchedCategory: 'greek_yogurt' },
      { name: 'Crushed Walnuts & Honey', estimatedPortion: '30g', estimatedPortionGrams: 30, calories: 160, matchedCategory: 'walnuts' },
      { name: 'Strawberries', estimatedPortion: '50g', estimatedPortionGrams: 50, calories: 25, matchedCategory: 'strawberries' },
    ],
    totalCalories: 315,
    macros: { proteinGrams: 22, carbsGrams: 26, fatGrams: 14 },
    condition: 'Fresh, probiotic-rich snack',
    healthTip: 'High protein content helps curb evening hunger cravings without disrupting sleep.',
    confidence: 0.97,
  },
];

async function seed() {
  let targetUidResolved = targetUid;
  if (targetEmail) {
    const userRecord = await getAuth().getUserByEmail(targetEmail);
    targetUidResolved = userRecord.uid;
  }
  console.log(`Target User UID: ${targetUidResolved}${targetEmail ? ` (resolved from ${targetEmail})` : ''}`);

  const userRef = db.collection('users').doc(targetUidResolved);

  // 1. Seed User Profile
  if (targetEmail) {
    // Real existing user — only backdate their "joined" date so the seeded window doesn't
    // predate account creation. Leave displayName/email/goals/etc. exactly as they are.
    console.log("Backdating joined date (createdAt) — not touching other profile fields...");
    await userRef.set({ createdAt: Date.now() - (WINDOW_DAYS + 2) * 86400000 }, { merge: true });
  } else {
    console.log('Seeding user profile...');
    const userProfile = {
      uid: targetUidResolved,
      displayName: 'Alex Perera',
      email: 'alex@lifesync.app',
      wakeTime: '06:30',
      workStart: '09:00',
      workEnd: '17:30',
      goals: ['fitness', 'study', 'work-life-balance'],
      dailyGoals: {
        calorieTarget: 2200,
        waterTargetMl: 2500,
        stepTarget: 8500,
      },
      notificationsEnabled: true,
      createdAt: Date.now() - (WINDOW_DAYS + 2) * 86400000,
    };
    await userRef.set(userProfile, { merge: true });
  }

  // 2. Seed Habits
  console.log('Seeding habits...');
  const habitsBatch = db.batch();
  for (const h of SAMPLE_HABITS) {
    const habitRef = userRef.collection('habits').doc(h.id);
    habitsBatch.set(habitRef, {
      id: h.id,
      title: h.title,
      preferredTime: h.preferredTime,
      recurring: h.recurring,
      daysOfWeek: h.daysOfWeek,
      createdAt: Timestamp.fromMillis(Date.now() - h.ageDays * 86400000),
    });
  }
  await habitsBatch.commit();

  // 3. Seed WINDOW_DAYS Days of Habit Logs
  console.log(`Seeding ${WINDOW_DAYS} days of habit completion logs...`);
  const logsBatch = db.batch();
  const allLogs: { habitId: string; date: string; completedAt: string | null; success: boolean }[] = [];

  for (let day = WINDOW_DAYS; day >= 0; day--) {
    const dateObj = daysAgoDate(day);
    const dateStr = formatDate(dateObj);
    const isWeekend = dateObj.getDay() === 0 || dateObj.getDay() === 6;

    for (const h of SAMPLE_HABITS) {
      const hourOffset = isWeekend ? (Math.random() > 0.5 ? 1 : 0) : 0;
      const completionHour = h.preferredHour + hourOffset;
      const isSuccess = Math.random() < h.consistency;

      const completedAt = isSuccess
        ? `${String(completionHour).padStart(2, '0')}:${String(Math.floor(Math.random() * 45)).padStart(2, '0')}`
        : null;

      const logId = `${h.id}_${dateStr}`;
      const logRef = userRef.collection('logs').doc(logId);
      const logData = {
        id: logId,
        habitId: h.id,
        date: dateStr,
        completedAt,
        success: isSuccess,
      };

      logsBatch.set(logRef, logData);
      allLogs.push(logData);
    }
  }
  await logsBatch.commit();

  // 4. Seed WINDOW_DAYS Days of Health Logs
  console.log(`Seeding ${WINDOW_DAYS} days of health logs (sleep, steps, water)...`);
  const healthBatch = db.batch();
  const sleepRecords: number[] = [];

  for (let day = WINDOW_DAYS; day >= 0; day--) {
    const dateObj = daysAgoDate(day);
    const dateStr = formatDate(dateObj);
    const isWeekend = dateObj.getDay() === 0 || dateObj.getDay() === 6;

    const sleepHours = Number((isWeekend ? 7.8 + Math.random() * 0.8 : 6.8 + Math.random() * 1.2).toFixed(1));
    const waterMl = Math.round((2200 + (Math.random() * 800 - 300)) / 100) * 100;
    const steps = Math.round(isWeekend ? 6500 + Math.random() * 5000 : 7500 + Math.random() * 4000);

    sleepRecords.push(sleepHours);

    const healthRef = userRef.collection('healthLogs').doc(dateStr);
    healthBatch.set(healthRef, {
      id: dateStr,
      date: dateStr,
      sleepHours,
      waterMl,
      steps,
    });
  }
  await healthBatch.commit();

  // 5. Seed WINDOW_DAYS Days of Food Logs
  console.log(`Seeding ${WINDOW_DAYS} days of food photo logs with nutrition analysis...`);
  const foodBatch = db.batch();
  for (let day = WINDOW_DAYS; day >= 0; day--) {
    const dateObj = daysAgoDate(day);
    const dateStr = formatDate(dateObj);
    const meal = SAMPLE_MEALS[day % SAMPLE_MEALS.length];

    const foodLogId = `food_${dateStr}_${day}`;
    const foodRef = userRef.collection('foodLogs').doc(foodLogId);
    foodBatch.set(foodRef, {
      id: foodLogId,
      date: dateStr,
      createdAt: dateObj.getTime(),
      foodItems: meal.items,
      totalCalories: meal.totalCalories,
      macros: meal.macros,
      condition: meal.condition,
      healthTip: meal.healthTip,
      confidence: meal.confidence,
    });
  }
  await foodBatch.commit();

  // 6. Pre-compute AI Recommendations using the trained ML model
  console.log('Generating & seeding live ML recommendations for all habits...');
  const recsBatch = db.batch();
  const now = new Date();
  const avgSleep = sleepRecords.slice(-14).reduce((a, b) => a + b, 0) / Math.min(sleepRecords.length, 14);

  for (const h of SAMPLE_HABITS) {
    const habitLogs = allLogs.filter((l) => l.habitId === h.id);
    const history: HourlyAttempt[] = habitLogs.map((l) => ({
      hour: Number((l.completedAt ?? h.preferredTime).split(':')[0]),
      daysAgo: Math.max(0, Math.floor((now.getTime() - new Date(l.date).getTime()) / 86400000)),
      success: l.success,
    }));

    const hourlySuccessRates = new Map<number, number>();
    for (const candHour of CANDIDATE_HOURS) {
      hourlySuccessRates.set(candHour, hourKernelSuccessRate(history, candHour, RECENCY_DECAY));
    }

    const context: MlContext = {
      isWeekend: now.getDay() === 0 || now.getDay() === 6,
      hourlySuccessRates,
      sleepHours: avgSleep,
      streakLength: 7,
      habitAgeDays: h.ageDays,
    };

    const { suggestedHour, probability } = recommendHourWithModel(context);
    const percent = Math.round(probability * 100);

    const recRef = userRef.collection('recommendations').doc(h.id);
    recsBatch.set(recRef, {
      habitId: h.id,
      suggestedTime: `${String(suggestedHour).padStart(2, '0')}:00`,
      score: Number(probability.toFixed(3)),
      reason: `ML model predicts ${percent}% success around ${String(suggestedHour).padStart(2, '0')}:00 based on your 30-day completion track record, ${avgSleep.toFixed(1)}h avg sleep, and active 7-day streak.`,
      generatedAt: now.getTime(),
    });
  }
  await recsBatch.commit();

  console.log('====================================================');
  console.log('Seeding complete! Database successfully populated:');
  console.log(`  - User Profile${targetEmail ? ` (joined date backdated ${WINDOW_DAYS + 2} days)` : ' (Alex Perera)'}`);
  console.log('  - 5 Active Habits');
  console.log(`  - ${5 * (WINDOW_DAYS + 1)} Habit Completion Logs (${WINDOW_DAYS} days)`);
  console.log(`  - ${WINDOW_DAYS + 1} Daily Health Metric Logs`);
  console.log(`  - ${WINDOW_DAYS + 1} Multimodal Food Logs`);
  console.log('  - 5 Pre-computed AI Habit Recommendations');
  console.log('====================================================');
}

seed().catch((err) => {
  console.error('Seeding error:', err);
  process.exit(1);
});